-- Requiring all endpoint related test modules
require "endpoints.CatTest.AliasesTest"
require "endpoints.CatTest.AllocationTest"
require "endpoints.CatTest.CountTest"
require "endpoints.CatTest.FieldDataTest"
require "endpoints.CatTest.HealthTest"
require "endpoints.CatTest.HelpTest"
require "endpoints.CatTest.IndicesTest"
require "endpoints.CatTest.MasterTest"
require "endpoints.CatTest.NodeAttrsTest"
require "endpoints.CatTest.NodesTest"
require "endpoints.CatTest.PendingTasksTest"
require "endpoints.CatTest.PluginsTest"
require "endpoints.CatTest.RecoveryTest"
