-- Requiring all endpoint related test modules
require "endpoints.EndpointTest"

require "endpoints.BulkTest"
require "endpoints.CountTest"
require "endpoints.CountPercolateTest"
require "endpoints.DeleteTest"
require "endpoints.DeleteByQueryTest"
require "endpoints.ExplainTest"
require "endpoints.FieldStatsTest"
require "endpoints.GetTest"
require "endpoints.IndexTest"
require "endpoints.InfoTest"
require "endpoints.MgetTest"
require "endpoints.MsearchTest"
require "endpoints.PingTest"
require "endpoints.ScrollTest"
require "endpoints.SearchTest"
require "endpoints.SearchExistsTest"
require "endpoints.SearchShardsTest"
require "endpoints.SearchTemplateTest"
require "endpoints.SuggestTest"
require "endpoints.UpdateTest"

require "endpoints.ClusterTest.init"
require "endpoints.IndicesTest.init"
require "endpoints.NodesTest.init"
