-- Requiring all endpoint related test modules
require "endpoints.EndpointTest"
require "endpoints.BulkTest"
require "endpoints.CountTest"
require "endpoints.DeleteTest"
require "endpoints.ExplainTest"
require "endpoints.FieldStatsTest"
require "endpoints.GetTest"
require "endpoints.IndexTest"
require "endpoints.InfoTest"
require "endpoints.MgetTest"
require "endpoints.PingTest"
