-- Requiring all endpoint related test modules
require "endpoints.IndicesTest.AnalyzeTest"
require "endpoints.IndicesTest.CloseTest"
require "endpoints.IndicesTest.CreateTest"
require "endpoints.IndicesTest.DeleteTest"
require "endpoints.IndicesTest.ExistsTest"
require "endpoints.IndicesTest.GetTest"
require "endpoints.IndicesTest.OpenTest"
require "endpoints.IndicesTest.OptimizeTest"
require "endpoints.IndicesTest.RefreshTest"
require "endpoints.IndicesTest.SealTest"
require "endpoints.IndicesTest.StatusTest"
