-- Requiring all endpoint related test modules
require "endpoints.SnapshotTest.CreateRepositoryTest"
require "endpoints.SnapshotTest.DeleteRepositoryTest"
require "endpoints.SnapshotTest.GetRepositoryTest"
require "endpoints.SnapshotTest.CreateTest"
require "endpoints.SnapshotTest.DeleteTest"
require "endpoints.SnapshotTest.GetTest"
require "endpoints.SnapshotTest.RestoreTest"
require "endpoints.SnapshotTest.StatusTest"
require "endpoints.SnapshotTest.VerifyRepositoryTest"
